apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bosch-service-b
spec:
  hosts:
  - bosch-service-b
  http:
  - route:
    - destination:
        host: bosch-service-b
    retries:
        attempts: 3
        perTryTimeout: 1s
        retryOn: 5xx